name: Synchronize to forked repo
on:
  push:
    branches:
      - main

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with: 
          token: ${ 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 }
          fetch-depth: 0
          ref: main

      - name: Add remote-url
        run: |
          git remote add forked-repo https://hyuke81:${ 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 }@github.com/hyuke81/Brachify_FE
          git config user.name hyuke81
          git config user.email ${ rmsidthgusdl81@gmail.com }
      
      - name: Push changes to forked-repo 
        run: |
          git push -f forked-repo main
      
      - name: Clean up
        run: |
          git remote remove forked-repo